# TCL File Generated by Component Editor 20.1
# Sat Nov 27 21:08:44 JST 2021
# DO NOT MODIFY


# 
# axi4lite_s "axi4lite_s" v1.0
#  2021.11.27.21:08:44
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi4lite_s
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi4lite_s
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi4lite_s
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi4lite_s
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4lite_s.v VERILOG PATH axi4lite_s.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL axi4lite_s
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file axi4lite_s.v VERILOG PATH axi4lite_s.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point axi4lite_slave
# 
add_interface axi4lite_slave axi4lite end
set_interface_property axi4lite_slave associatedClock clock_sink
set_interface_property axi4lite_slave associatedReset reset_sink
set_interface_property axi4lite_slave readAcceptanceCapability 1
set_interface_property axi4lite_slave writeAcceptanceCapability 1
set_interface_property axi4lite_slave combinedAcceptanceCapability 1
set_interface_property axi4lite_slave readDataReorderingDepth 1
set_interface_property axi4lite_slave bridgesToMaster ""
set_interface_property axi4lite_slave ENABLED true
set_interface_property axi4lite_slave EXPORT_OF ""
set_interface_property axi4lite_slave PORT_NAME_MAP ""
set_interface_property axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port axi4lite_slave axi4lite_slave_araddr araddr Input 8
add_interface_port axi4lite_slave axi4lite_slave_arready arready Output 1
add_interface_port axi4lite_slave axi4lite_slave_awaddr awaddr Input 8
add_interface_port axi4lite_slave axi4lite_slave_awready awready Output 1
add_interface_port axi4lite_slave axi4lite_slave_arvalid arvalid Input 1
add_interface_port axi4lite_slave axi4lite_slave_awvalid awvalid Input 1
add_interface_port axi4lite_slave axi4lite_slave_rdata rdata Output 32
add_interface_port axi4lite_slave axi4lite_slave_rready rready Input 1
add_interface_port axi4lite_slave axi4lite_slave_rvalid rvalid Output 1
add_interface_port axi4lite_slave axi4lite_slave_wdata wdata Input 32
add_interface_port axi4lite_slave axi4lite_slave_wready wready Output 1
add_interface_port axi4lite_slave axi4lite_slave_wstrb wstrb Input 4
add_interface_port axi4lite_slave axi4lite_slave_wvalid wvalid Input 1
add_interface_port axi4lite_slave axi4lite_slave_arprot arprot Input 3
add_interface_port axi4lite_slave axi4lite_slave_awprot awprot Input 3
add_interface_port axi4lite_slave axi4lite_slave_bready bready Input 1
add_interface_port axi4lite_slave axi4lite_slave_bresp bresp Output 2
add_interface_port axi4lite_slave axi4lite_slave_bvalid bvalid Output 1
add_interface_port axi4lite_slave axi4lite_slave_rresp rresp Output 2

