# TCL File Generated by Component Editor 20.1
# Sat Nov 27 20:21:45 JST 2021
# DO NOT MODIFY


# 
# axi4stream_m "axi4stream_m" v1.0
#  2021.11.27.20:21:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi4stream_m
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi4stream_m
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi4stream_m
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point axi4stream_master
# 
add_interface axi4stream_master axi4stream start
set_interface_property axi4stream_master associatedClock clock_sink
set_interface_property axi4stream_master associatedReset reset_sink
set_interface_property axi4stream_master ENABLED true
set_interface_property axi4stream_master EXPORT_OF ""
set_interface_property axi4stream_master PORT_NAME_MAP ""
set_interface_property axi4stream_master CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_master SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_master axi4stream_master_tdata tdata Output 8
add_interface_port axi4stream_master axi4stream_master_tdest tdest Output 1
add_interface_port axi4stream_master axi4stream_master_tid tid Output 1
add_interface_port axi4stream_master axi4stream_master_tkeep tkeep Output 1
add_interface_port axi4stream_master axi4stream_master_tlast tlast Output 1
add_interface_port axi4stream_master axi4stream_master_tready tready Input 1
add_interface_port axi4stream_master axi4stream_master_tstrb tstrb Output 1
add_interface_port axi4stream_master axi4stream_master_tuser tuser Output 1
add_interface_port axi4stream_master axi4stream_master_tvalid tvalid Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1

