# TCL File Generated by Component Editor 20.1
# Sat Nov 27 20:01:13 JST 2021
# DO NOT MODIFY


# 
# axi4_m "axi4_m" v1.0
#  2021.11.27.20:01:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi4_m
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi4_m
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi4_m
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi4_m
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4_m.v VERILOG PATH axi4_m.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL axi4_m
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4_m.v VERILOG PATH axi4_m.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point axm_m0
# 
add_interface axm_m0 axi4 start
set_interface_property axm_m0 associatedClock clock
set_interface_property axm_m0 associatedReset reset
set_interface_property axm_m0 readIssuingCapability 1
set_interface_property axm_m0 writeIssuingCapability 1
set_interface_property axm_m0 combinedIssuingCapability 1
set_interface_property axm_m0 ENABLED true
set_interface_property axm_m0 EXPORT_OF ""
set_interface_property axm_m0 PORT_NAME_MAP ""
set_interface_property axm_m0 CMSIS_SVD_VARIABLES ""
set_interface_property axm_m0 SVD_ADDRESS_GROUP ""

add_interface_port axm_m0 axm_m0_awaddr awaddr Output 32
add_interface_port axm_m0 axm_m0_awprot awprot Output 3
add_interface_port axm_m0 axm_m0_awvalid awvalid Output 1
add_interface_port axm_m0 axm_m0_awready awready Input 1
add_interface_port axm_m0 axm_m0_wdata wdata Output 32
add_interface_port axm_m0 axm_m0_wlast wlast Output 1
add_interface_port axm_m0 axm_m0_wvalid wvalid Output 1
add_interface_port axm_m0 axm_m0_wready wready Input 1
add_interface_port axm_m0 axm_m0_bvalid bvalid Input 1
add_interface_port axm_m0 axm_m0_bready bready Output 1
add_interface_port axm_m0 axm_m0_araddr araddr Output 32
add_interface_port axm_m0 axm_m0_arprot arprot Output 3
add_interface_port axm_m0 axm_m0_arvalid arvalid Output 1
add_interface_port axm_m0 axm_m0_arready arready Input 1
add_interface_port axm_m0 axm_m0_rdata rdata Input 32
add_interface_port axm_m0 axm_m0_rvalid rvalid Input 1
add_interface_port axm_m0 axm_m0_rready rready Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1

